document.writeln("<script src=\"/js/flexible.js\"></script>");
document.writeln("<link rel=\"stylesheet\" href=\"/commonJs/css/common.css\" />");
document.writeln("<script src=\"/templets/houtai/js/jquery-1.8.3.min.js\"></script>");
document.writeln("<script type=\"text/javascript\" src=\"/templets/houtai/js/jquery.SuperSlide.2.1.1.js\"></script>");

document.writeln("<div id=\"head\" class=\"clearfix\">");
document.writeln("			<div class=\"head_top relative\">");
document.writeln("				<div class=\"leftBut absolute\"></div>");
document.writeln("				<a href=\"/\" target=\"_blank\" class=\"logo\"></a>");
document.writeln("				<div class=\"rightBut absolute\"></div>");
document.writeln("			</div>");
document.writeln("			<div class=\"head_xl\" id=\"head_xl\">");
document.writeln("				<div class=\"selectList absolute\">");
document.writeln("					<ul>");
document.writeln("						<em></em>");
document.writeln("						<li><a href=\"/about/zjwd.html\" rel=\'dropmenu2\'>走进王东 <i></i></a></li>	      	");
document.writeln("						<li><a href=\'/about/tsjs.html\' rel=\'dropmenu6\'>特色技术 <i></i></a></li>	      	");
document.writeln("						<li><a href=\"/about/mxln.html\" rel=\'dropmenu7\'>美学理念 <i></i></a></li>");
document.writeln("						<li><a href=\"/about/yswd.html\" rel=\'dropmenu8\'>艺术王东 <i></i></a></li>");
document.writeln("						<li><a href=\"/about/xsdw.html\" rel=\'dropmenu7\'>学术地位 <i></i></a></li>");
document.writeln("						<li><a href=\"/about/yxwd.html\" rel=\'dropmenu8\'>映像王东 <i></i></a></li>");
document.writeln("					</ul>");
document.writeln("				</div>");
document.writeln("				<div class=\"zg1\"></div>");
document.writeln("				<div class=\"popMenus\">");
document.writeln("					<div class=\"menuNavs clearfix\">");
document.writeln("						<ul>");
document.writeln("							<em></em>");
document.writeln("							<li class=\"lmlist\"><i></i><span>特色项目</span></li>");
document.writeln("							<li class=\"lmlist\"><i></i><span>面部塑形</span></li>");
document.writeln("							<li class=\"lmlist\"><i></i><span>面部抗衰</span></li>");
document.writeln("							<li class=\"lmlist\"><i></i><span>形体雕塑</span></li>");
document.writeln("							<li class=\"lmlist\"><i></i><span>失败修复</span></li>");
document.writeln("						</ul>");
document.writeln("					</div>");
document.writeln("					<div class=\"menuContents\">");
document.writeln("						<div class=\"menu_qh clearfix\">");
document.writeln("							<ul>");
document.writeln("								<li>");
document.writeln("									<a href=\"/zt/bkdjqg/\" target=\"_blank\">");
document.writeln("									<em><img src=\"/commonJs/ztimg/ts1.png\" width=\"100%\"></em>");
document.writeln("									<span>降颧骨</span>");
document.writeln("									</a>");
document.writeln("								</li>");
document.writeln("								<li>");
document.writeln("									<a href=\"/zt/xlcxs/\" target=\"_blank\">");
document.writeln("									<em><img src=\"/commonJs/ztimg/ts2.png\" width=\"100%\"></em>");
document.writeln("									<span>去下颌角</span>");
document.writeln("									</a>");
document.writeln("								</li>");
document.writeln("								<li>");
document.writeln("									<a href=\"/project/mbsx/qsxb/\" target=\"_blank\">");
document.writeln("									<em><img src=\"/commonJs/ztimg/ts3.png\" width=\"100%\"></em>");
document.writeln("									<span>去双下巴</span>");
document.writeln("									</a>");
document.writeln("								</li>");
document.writeln("							</ul>");
document.writeln("						</div>");
document.writeln("						<div class=\"menu_qh clearfix\">");
document.writeln("							<ul>");
document.writeln("								<li>");
document.writeln("									<a href=\"/zt/fet3/\" target=\"_blank\">");
document.writeln("									<em><img src=\"/commonJs/xmimg/xm6.png\" width=\"100%\"></em>");
document.writeln("									<span>丰额头</span>");
document.writeln("									</a>");
document.writeln("								</li>");
document.writeln("								<li>");
document.writeln("									<a href=\"/zt/fpgj3/\" target=\"_blank\">");
document.writeln("									<em><img src=\"/commonJs/xmimg/xm7.png\" width=\"100%\"></em>");
document.writeln("									<span>丰苹果肌</span>");
document.writeln("									</a>");
document.writeln("								</li>");
document.writeln("								<li>");
document.writeln("									<a href=\"/zt/fxb3/\" target=\"_blank\">");
document.writeln("									<em><img src=\"/commonJs/xmimg/xm8.png\" width=\"100%\"></em>");
document.writeln("									<span>丰下巴</span>");
document.writeln("									</a>");
document.writeln("								</li>");
document.writeln("								<li>");
document.writeln("									<a href=\"/project/mbsx/flg/\" target=\"_blank\">");
document.writeln("									<em><img src=\"/commonJs/xmimg/xm9.png\" width=\"100%\"></em>");
document.writeln("									<span>丰泪沟</span>");
document.writeln("									</a>");
document.writeln("								</li>");
document.writeln("								<li>");
document.writeln("									<a href=\"/zt/ftyx3/\" target=\"_blank\">");
document.writeln("									<em><img src=\"/commonJs/xmimg/xm10.png\" width=\"100%\"></em>");
document.writeln("									<span>丰太阳穴</span>");
document.writeln("									</a>");
document.writeln("								</li>");
document.writeln("								<li>");
document.writeln("									<a href=\"/project/mbsx/fmj/\" target=\"_blank\">");
document.writeln("									<em><img src=\"/commonJs/xmimg/xm11.png\" width=\"100%\"></em>");
document.writeln("									<span>丰面颊</span>");
document.writeln("									</a>");
document.writeln("								</li>");
document.writeln("								<li>");
document.writeln("									<a href=\"/project/mbsx/fyw/\" target=\"_blank\">");
document.writeln("									<em><img src=\"/commonJs/xmimg/xm12.png\" width=\"100%\"></em>");
document.writeln("									<span>丰眼窝</span>");
document.writeln("									</a>");
document.writeln("								</li>");
document.writeln("								<li>");
document.writeln("									<a href=\"/project/mbsx/fc/\" target=\"_blank\">");
document.writeln("									<em><img src=\"/commonJs/xmimg/xm13.png\" width=\"100%\"></em>");
document.writeln("									<span>丰  唇</span>");
document.writeln("									</a>");
document.writeln("								</li>");
document.writeln("								<li>");
document.writeln("									<a href=\"/project/mbsx/fxhy/\" target=\"_blank\">");
document.writeln("									<em><img src=\"/commonJs/xmimg/xm14.png\" width=\"100%\"></em>");
document.writeln("									<span>丰下颌缘</span>");
document.writeln("									</a>");
document.writeln("								</li>");
document.writeln("								<li>");
document.writeln("									<a href=\"/project/mbsx/fwc/\" target=\"_blank\">");
document.writeln("									<em><img src=\"/commonJs/xmimg/xm15.png\" width=\"100%\"></em>");
document.writeln("									<span>丰卧蚕</span>");
document.writeln("									</a>");
document.writeln("								</li>");
document.writeln("								<li>");
document.writeln("									<a href=\"/project/mbsx/fmg/\" target=\"_blank\">");
document.writeln("									<em><img src=\"/commonJs/xmimg/xm16.png\" width=\"100%\"></em>");
document.writeln("									<span>丰眉弓</span>");
document.writeln("									</a>");
document.writeln("								</li>");
document.writeln("								<li>");
document.writeln("									<a href=\"/zt/lb/\" target=\"_blank\">");
document.writeln("									<em><img src=\"/commonJs/xmimg/xm17.png\" width=\"100%\"></em>");
document.writeln("									<span>隆  鼻</span>");
document.writeln("									</a>");
document.writeln("								</li>");
document.writeln("							</ul>");
document.writeln("						</div>");
document.writeln("						<div class=\"menu_qh clearfix\">");
document.writeln("							<ul>");
document.writeln("								<li>");
document.writeln("									<a href=\"/project/mbks/flw/\" target=\"_blank\">");
document.writeln("									<em><img src=\"/commonJs/xmimg/xm18.png\" width=\"100%\"></em>");
document.writeln("									<span>法令纹</span>");
document.writeln("									</a>");
document.writeln("								</li>");
document.writeln("								<li>");
document.writeln("									<a href=\"/project/mbks/ttw/\" target=\"_blank\">");
document.writeln("									<em><img src=\"/commonJs/xmimg/xm19.png\" width=\"100%\"></em>");
document.writeln("									<span>抬头纹</span>");
document.writeln("									</a>");
document.writeln("								</li>");
document.writeln("								<li>");
document.writeln("									<a href=\"/project/mbks/czw/\" target=\"_blank\">");
document.writeln("									<em><img src=\"/commonJs/xmimg/xm20.png\" width=\"100%\"></em>");
document.writeln("									<span>唇周纹</span>");
document.writeln("									</a>");
document.writeln("								</li>");
document.writeln("								<li>");
document.writeln("									<a href=\"/project/mbks/yzw/\" target=\"_blank\">");
document.writeln("									<em><img src=\"/commonJs/xmimg/xm21.png\" width=\"100%\"></em>");
document.writeln("									<span>眼周纹</span>");
document.writeln("									</a>");
document.writeln("								</li>");
document.writeln("								<li>");
document.writeln("									<a href=\"/project/mbks/mjw/\" target=\"_blank\">");
document.writeln("									<em><img src=\"/commonJs/xmimg/xm22.png\" width=\"100%\"></em>");
document.writeln("									<span>眉间纹</span>");
document.writeln("									</a>");
document.writeln("								</li>");
document.writeln("							</ul>");
document.writeln("						</div>");
document.writeln("						<div class=\"menu_qh clearfix\">");
document.writeln("							<ul>");
document.writeln("								<li>");
document.writeln("									<a href=\"/project/xtds/tbsx/\" target=\"_blank\">");
document.writeln("									<em><img src=\"/commonJs/xmimg/xm23.png\" width=\"100%\"></em>");
document.writeln("									<span>臀部塑形</span>");
document.writeln("									</a>");
document.writeln("								</li>");
document.writeln("								<li>");
document.writeln("									<a href=\"/zt/fcyxcss/\" target=\"_blank\">");
document.writeln("									<em><img src=\"/commonJs/xmimg/xm24.png\" width=\"100%\"></em>");
document.writeln("									<span>腰部塑形</span>");
document.writeln("									</a>");
document.writeln("								</li>");
document.writeln("								<li>");
document.writeln("									<a href=\"/zt/ptfxczs/\" target=\"_blank\">");
document.writeln("									<em><img src=\"/commonJs/xmimg/xm25.png\" width=\"100%\"></em>");
document.writeln("									<span>腹部塑形</span>");
document.writeln("									</a>");
document.writeln("								</li>");
document.writeln("								<li>");
document.writeln("									<a href=\"/project/xtds/fx/\" target=\"_blank\">");
document.writeln("									<em><img src=\"/commonJs/xmimg/xm26.png\" width=\"100%\"></em>");
document.writeln("									<span>丰  胸</span>");
document.writeln("									</a>");
document.writeln("								</li>");
document.writeln("								<li>");
document.writeln("									<a href=\"/project/xtds/dtsx/\" target=\"_blank\">");
document.writeln("									<em><img src=\"/commonJs/xmimg/xm27.png\" width=\"100%\"></em>");
document.writeln("									<span>腿部塑形</span>");
document.writeln("									</a>");
document.writeln("								</li>");
document.writeln("								<li>");
document.writeln("									<a href=\"/project/xtds/oxtjz/\" target=\"_blank\">");
document.writeln("									<em><img src=\"/commonJs/xmimg/xm28.png\" width=\"100%\"></em>");
document.writeln("									<span>O型腿矫正</span>");
document.writeln("									</a>");
document.writeln("								</li>");
document.writeln("								<li>");
document.writeln("									<a href=\"/zt/shbzzs/\" target=\"_blank\">");
document.writeln("									<em><img src=\"/commonJs/xmimg/xm29.png\" width=\"100%\"></em>");
document.writeln("									<span>背部塑形</span>");
document.writeln("									</a>");
document.writeln("								</li>");
document.writeln("								<li>");
document.writeln("									<a href=\"/zt/llbzzs/\" target=\"_blank\">");
document.writeln("									<em><img src=\"/commonJs/xmimg/xm30.png\" width=\"100%\"></em>");
document.writeln("									<span>手臂塑形</span>");
document.writeln("									</a>");
document.writeln("								</li>");
document.writeln("								<li>");
document.writeln("									<a href=\"/project/xtds/kjsz/\" target=\"_blank\">");
document.writeln("									<em><img src=\"/commonJs/xmimg/xm31.png\" width=\"100%\"></em>");
document.writeln("									<span>宽肩缩窄</span>");
document.writeln("									</a>");
document.writeln("								</li>");
document.writeln("								<li>");
document.writeln("									<a href=\"/project/xtds/xtsx/\" target=\"_blank\">");
document.writeln("									<em><img src=\"/commonJs/xmimg/xm32.png\" width=\"100%\"></em>");
document.writeln("									<span>小腿塑形</span>");
document.writeln("									</a>");
document.writeln("								</li>");
document.writeln("							</ul>");
document.writeln("						</div>");
document.writeln("						<div class=\"menu_qh clearfix\">");
document.writeln("							<ul>");
document.writeln("								<li>");
document.writeln("									<a href=\"/zt/xzsbxf/\" target=\"_blank\">");
document.writeln("									<em><img src=\"/commonJs/xmimg/xm33.png\" width=\"100%\"></em>");
document.writeln("									<span>吸脂失败");
document.writeln("									修复</span>");
document.writeln("									</a>");
document.writeln("								</li>");
document.writeln("								<li>");
document.writeln("									<a href=\"/zt/zfyzsbxf/\" target=\"_blank\">");
document.writeln("									<em><img src=\"/commonJs/xmimg/xm34.png\" width=\"100%\"></em>");
document.writeln("									<span>脂肪填充");
document.writeln("									失败修复</span>");
document.writeln("									</a>");
document.writeln("								</li>");
document.writeln("								<li>");
document.writeln("									<a href=\"/project/sbxf/ywzs/\" target=\"_blank\">");
document.writeln("									<em><img src=\"/commonJs/xmimg/xm35.png\" width=\"100%\"></em>");
document.writeln("									<span>异物注射");
document.writeln("									失败修复</span>");
document.writeln("									</a>");
document.writeln("								</li>");
document.writeln("								<li>");
document.writeln("									<a href=\"/project/sbxf/szyz/\" target=\"_blank\">");
document.writeln("									<em><img src=\"/commonJs/xmimg/xm36.png\" width=\"100%\"></em>");
document.writeln("									<span>生长因子");
document.writeln("									增生修复</span>");
document.writeln("									</a>");
document.writeln("								</li>");
document.writeln("							</ul>");
document.writeln("						</div>");
document.writeln("					</div>");
document.writeln("				</div>");
document.writeln("				<script type=\"text/javascript\">jQuery(\".popMenus\").slide({ titCell:\".menuNavs li\", mainCell:\".menuContents\", trigger:\"click\",delayTime:0 });</script>");
document.writeln("				<div class=\"zg\"></div>");
document.writeln("				<script src=\"/commonJs/js/yzg.js\"></script>");
document.writeln("			</div>");
document.writeln("   		</div>");