// JavaScript Document

document.writeln("		<div class=\'hjSlides_new relative\' id=\'hjSlides_new\'>");
document.writeln("			<ul class=\'hjSlides_container\'>");
document.writeln("				<li>");
document.writeln("					<ol>");
document.writeln("						<img src=\'/templets/houtai/img/hj1_1.jpg\'/>");
document.writeln("						<img src=\'/templets/houtai/img/hj1_2.jpg\'/>");
document.writeln("						<img src=\'/templets/houtai/img/hj1_3.jpg\'/>");
document.writeln("					</ol>");
document.writeln("					<div>");
document.writeln("						<h2>Y I M E I</h2>");
document.writeln("						<span>北京CBD铂金地段</span>");
document.writeln("						<p>位于北京朝阳区CBD铂金地段，潮流前卫，顶级时尚，与卢浮宫同系的建筑风格，是众多高端名媛汇聚的顶级医美品牌。</p>");
document.writeln("					</div>");
document.writeln("				</li>");
document.writeln("				<li>");
document.writeln("					<ol>");
document.writeln("						<img src=\'/templets/houtai/img/hj2_1.jpg\' width=\'100%\'/>");
document.writeln("						<img src=\'/templets/houtai/img/hj2_2.jpg\' width=\'100%\'/>");
document.writeln("						<img src=\'/templets/houtai/img/hj2_3.jpg\' width=\'100%\'/>");
document.writeln("					</ol>");
document.writeln("					<div>");
document.writeln("						<h2>Y I M E I</h2>");
document.writeln("						<span>安全流程环环把控</span>");
document.writeln("						<p>艺美整合了国际先进的安全诊疗设备、德国千级层流手术室、术前身体隐患排查、术中麻醉机制管控、术后维养管理，为您提供最切实的保障</p>");
document.writeln("					</div>");
document.writeln("				</li>");
document.writeln("				<li>");
document.writeln("					<ol>");
document.writeln("						<img src=\'/templets/houtai/img/hj3_1.jpg\' width=\'100%\'/>");
document.writeln("						<img src=\'/templets/houtai/img/hj3_2.jpg\' width=\'100%\'/>");
document.writeln("						<img src=\'/templets/houtai/img/hj3_3.jpg\' width=\'100%\'/>");
document.writeln("					</ol>");
document.writeln("					<div class=\'hj_rg\'>");

document.writeln("						<h2>Y I M E I</h2>");
document.writeln("						<span>奢华私密环境体验</span>");
document.writeln("						<p>从求美者的角度出发，充分保证求美者的隐私性、舒适度体验感，每一位莅临艺美的客人都能享受至尊美丽体验</p>");
document.writeln("					</div>");
document.writeln("				</li>");
document.writeln("				<li>");
document.writeln("					<ol>");
document.writeln("						<img src=\'/templets/houtai/img/hj4_1.jpg\' width=\'100%\'/>");
document.writeln("						<img src=\'/templets/houtai/img/hj4_2.jpg\' width=\'100%\'/>");
document.writeln("						<img src=\'/templets/houtai/img/hj4_3.jpg\' width=\'100%\'/>");
document.writeln("					</ol>");
document.writeln("					<div>");
document.writeln("						<h2>Y I M E I</h2>");
document.writeln("						<span>订制服务终身私享</span>");
document.writeln("						<p>专车接送、生日惊喜、订制服务、全年跟踪、终身美丽管理，想您所想，如您所愿，艺美与您终身之约</p>");
document.writeln("					</div>");
document.writeln("				</li>");
document.writeln("			</ul>");
document.writeln("			<div class=\'hjSlides_foncus absolute\'> </div>");
document.writeln("		</div>");
document.writeln("		<script>");
document.writeln("			TouchSlide({ slideCell:\'#hjSlides_new\',titCell:\'.hjSlides_foncus\',mainCell:\'.hjSlides_container\',autoPage:\'<span></span>\',effect:\'leftLoop\',delayTime:600,interTime:6000,autoPlay:true,titOnClassName:\'active\' });");
document.writeln("		</script>");